# Generated by Django 5.1.1 on 2025-08-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion_peso', '0002_alter_clasificacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasificacion',
            options={'verbose_name': 'Clasificación de peso', 'verbose_name_plural': 'Clasificaciones de peso'},
        ),
    ]
