# Generated by Django 5.1.1 on 2025-08-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion_peso', '0003_alter_clasificacion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificacion',
            name='imc_max',
            field=models.FloatField(default=0, verbose_name='IMC máximo'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='imc_min',
            field=models.FloatField(default=0, verbose_name='IMC mínimo'),
        ),
    ]
