# Generated by Django 5.1.1 on 2025-08-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comida_diaria', '0003_alter_comida_diaria_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comida_diaria',
            options={'verbose_name': 'Consumo de comida diaria', 'verbose_name_plural': 'Consumos de comida diaria'},
        ),
    ]
