# Generated by Django 5.1.1 on 2025-08-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antecedentes_familiares', '0003_alter_antecedentes_familiares_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antecedentes_familiares',
            options={'verbose_name': 'Antecedente familiar', 'verbose_name_plural': '¿Tiene antecedentes familiares de obesidad?'},
        ),
    ]
