# Generated by Django 5.1.1 on 2025-05-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tiempo_en_pantallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Cuantas horas al día pasas frente a las pantallas (TV, videojuegos, celular)')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Tiempo frente a las pantallas  (TV, videojuegos, celular) por día',
                'verbose_name_plural': 'Tiempo frente a las pantallas  (TV, videojuegos, celular) por día',
            },
        ),
    ]
