# Generated by Django 5.1.1 on 2025-08-24 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clasificacion_peso', '0004_clasificacion_imc_max_clasificacion_imc_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendacionesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Terapéutico', 'Terapéutico'), ('Preventivo', 'Preventivo')], max_length=20, verbose_name='Tipo de plan')),
                ('recomendaciones', models.TextField(verbose_name='Recomendación o plan')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clasificacion_peso.clasificacion', verbose_name='Clasificación de peso')),
            ],
            options={
                'verbose_name': 'Recomendaciones o planes',
                'verbose_name_plural': 'Recomendaciones o planes',
            },
        ),
    ]
