# Generated by Django 5.1.1 on 2025-05-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conforme_con_cuerpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='¿Te sientes conforme con tu cuerpo o peso?')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': '¿Te sientes conforme con tu cuerpo o peso?',
                'verbose_name_plural': '¿Te sientes conforme con tu cuerpo o peso?',
            },
        ),
    ]
