# Generated by Django 5.1.1 on 2025-08-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conforme_con_cuerpo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conforme_con_cuerpo',
            options={'verbose_name': 'CONFORME CON EL CUERPO', 'verbose_name_plural': '¿Te sientes conforme con tu cuerpo o peso?'},
        ),
    ]
