# Generated by Django 5.1.1 on 2025-08-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condiciones_medicas', '0003_alter_condiciones_medicas_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condiciones_medicas',
            options={'verbose_name': 'Condición médica', 'verbose_name_plural': 'Condiciones médicas'},
        ),
    ]
