# Generated by Django 5.1.1 on 2025-08-10 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clasificacion_peso', '0003_alter_clasificacion_options'),
        ('comida_diaria', '0004_alter_comida_diaria_options'),
        ('genero', '0003_alter_genero_options'),
        ('habitos_alimentarios', '0001_initial'),
        ('horas_de_sueno', '0001_initial'),
        ('tiempo_en_pantallas', '0001_initial'),
        ('tipo_de_transporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso')),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Estatura')),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IMC')),
                ('perimetro_cintura', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Perímetro de cintura')),
                ('perimetro_cadera', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Perímetro de cadera')),
                ('consumo_comida_rapida', models.BooleanField(verbose_name='¿Consumes comida rapida?')),
                ('consumo_frutas_verduras', models.BooleanField(verbose_name='¿Consumes frutas y verduras?')),
                ('consumo_alcohol', models.BooleanField(verbose_name='¿Consúmes bebidas alcoholicas?')),
                ('estres_ansiedad', models.BooleanField(verbose_name='¿Súfres de estrés o ansiedad?')),
                ('conforme_con_cuerpo', models.BooleanField(verbose_name='¿Te siéntes conforme con tu cuerpo o peso?')),
                ('actividades_fisicas', models.BooleanField(verbose_name='¿Realízas Actividades fisicas?')),
                ('antecedentes_familiares', models.BooleanField(default=1, verbose_name='¿Tienes antecedentes familiares de obesidad en tu familia?')),
                ('entorno_social', models.BooleanField(verbose_name='¿Tienes entorno social con obesidad (amistades, compañeros, o con los que frecuenta)?')),
                ('condiciones_medicas', models.BooleanField(verbose_name='¿Tienes condiciones medicas como: diabetes tipo 2, presion arterial o colesterol alto?')),
                ('consumo_medicamentos', models.BooleanField(verbose_name='¿Consumes medicamentos que puedan alterar el peso?')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('clasificacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clasificacion_peso.clasificacion', verbose_name='Clasificación de peso')),
                ('comida_diaria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comida_diaria.comida_diaria', verbose_name='¿Cuántas veces comes al dia?')),
                ('genero', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='genero.genero', verbose_name='Género')),
                ('habitos_alimentarios', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='habitos_alimentarios.habitos_alimentarios', verbose_name='¿Comes en casa o fuera frecuentemente?')),
                ('horas_de_sueno', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='horas_de_sueno.horas_de_sueno', verbose_name='¿Cuántas horas descansas por la noche?')),
                ('tiempo_en_pantallas', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tiempo_en_pantallas.tiempo_en_pantallas', verbose_name='¿Cuánto tiempo pasas frente a las pantallas (TV, videojuegos, celular)?')),
                ('tipo_de_transporte', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tipo_de_transporte.tipo_de_transporte', verbose_name='¿Caminas al colegio o  te transportas en vehiculo?')),
            ],
            options={
                'verbose_name': 'DATOS DE PERSONAS',
                'verbose_name_plural': 'DATOS DE PERSONAS',
            },
        ),
    ]
