# Generated by Django 5.1.1 on 2025-08-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='actividades_fisicas',
            field=models.BooleanField(default=0, verbose_name='¿Realízas Actividades fisicas?'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='antecedentes_familiares',
            field=models.BooleanField(default=0, verbose_name='¿Tienes antecedentes familiares de obesidad en tu familia?'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='condiciones_medicas',
            field=models.BooleanField(default=0, verbose_name='¿Tienes condiciones medicas como: diabetes tipo 2, presion arterial o colesterol alto?'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='conforme_con_cuerpo',
            field=models.BooleanField(default=0, verbose_name='¿Te siéntes conforme con tu cuerpo o peso?'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='consumo_alcohol',
            field=models.BooleanField(default=0, verbose_name='¿Consúmes bebidas alcoholicas?'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='consumo_comida_rapida',
            field=models.BooleanField(default=0, verbose_name='¿Consumes comida rapida?'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='consumo_frutas_verduras',
            field=models.BooleanField(default=0, verbose_name='¿Consumes frutas y verduras?'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='consumo_medicamentos',
            field=models.BooleanField(default=0, verbose_name='¿Consumes medicamentos que puedan alterar el peso?'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='entorno_social',
            field=models.BooleanField(default=0, verbose_name='¿Tienes entorno social con obesidad (amistades, compañeros, o con los que frecuenta)?'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='estres_ansiedad',
            field=models.BooleanField(default=0, verbose_name='¿Súfres de estrés o ansiedad?'),
        ),
    ]
