# Generated by Django 5.1.1 on 2025-08-10 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida_diaria', '0004_alter_comida_diaria_options'),
        ('personas', '0002_alter_personas_actividades_fisicas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='comida_diaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comida_diaria.comida_diaria', verbose_name='¿Cuántas veces comes al dia?'),
        ),
    ]
